# APIs ALAN NICOLAS
OPENAI_API_KEY = "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"
CLAUDE_API_KEY = "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"

GROQ_API_KEY = "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"
MISTRALAI_API_KEY = "NUBvbpFkWKBTU3nBZOkZgBKjWsTB0d4X"
GEMINI_API_KEY = "AIzaSyB7Xy3EipZk_QzEB-2e41dnW0fzdSuCkwA"
HUGGINGFACEHUB_API_TOKEN = "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"
LANGCHAIN_API_KEY = "ls__941dd230188843a5aa51158ae72e7c9c"
LANGCHAIN_TRACING_V2 = true
AGENTOPS_API_KEY = "17eab40f-a675-4cc8-a027-056f816b8fa5"
TOGETHER_API_KEY = "b499dfd5a156dfa342e43b0341f32fbb2ceb8bc69c69544aa43d6cf613bfb4d5"

SERPER_API_KEY = "5293a322b9bf5ef6b8a5c7c1d14f39347f9608af"
EXA_API_KEY = "953632bb-3b74-4488-adad-7cd0002016e9"

EVO_INSTANCE = "Pinnaclo_0854"
EVO_TOKEN = "8ldf1tpx8149rfb58aemhh"

YT_API_KEY = "AIzaSyB52Rzm9xp_dsGbo7PW3Llt4ouXw_k22sA"

GSHEETS_CREDENTIALS = "./credentials/cred_gsheets.json"
GSHEETS_TOKEN = "./credentials/token_gsheets.json"
SPREADSHEET_ID = "14f0ux19a78Q0B_V1aXu0aWaRP8rvR_AWU3ewbEHIz98"

GDRIVE_CREDENTIALS = "./credentials/cred_gdrive.json"
GDRIVE_FOLDER_PROJECTS = "1_yXPNTof80dSJakKCqbYXDk1YowtUOaZ"

DB_HOST_POSTGRE = "35.198.28.112"
DB_PORT_POSTGRE = 5432
DB_NAME_POSTGRE = "pinnaclo-db"
DB_USER_POSTGRE = "luandetoni"
DB_PASSWORD_POSTGRE = "Pinnaclo@9010"
